import { Activity, CalendarDays, IndianRupee, Plus, Search, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import Navbar from "../components/Navbar";
import api from "../lib/api";
import { formatCurrency, formatDate } from "../lib/format";
import { Spinner } from "../components/Loading";

export default function AdminDashboard(){
  const [stats,setStats]=useState({}); const [doctors,setDoctors]=useState([]); const [users,setUsers]=useState([]); const [appointments,setAppointments]=useState([]); const [tab,setTab]=useState("overview"); const [showAdd,setShowAdd]=useState(false);
  async function load(){try{const [s,d,u,a]=await Promise.all([api.get("/admin/stats"),api.get("/admin/doctors"),api.get("/admin/users"),api.get("/admin/appointments")]);setStats(s.data);setDoctors(d.data);setUsers(u.data);setAppointments(a.data)}catch(e){toast.error(e.response?.data?.message||"Admin data unavailable.")}}
  useEffect(()=>{load()},[]);
  async function remove(id){if(!confirm("Deactivate this doctor?"))return;try{await api.delete(`/admin/doctors/${id}`);toast.success("Doctor deactivated.");load()}catch(e){toast.error(e.response?.data?.message||"Could not deactivate.")}}

  return <>
    <Navbar/><main className="min-h-screen bg-slate-50/70 py-8"><div className="container-app">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-teal-600">Administration</p><h1 className="mt-1 text-3xl font-black text-ink">MediBook control center</h1><p className="mt-2 text-sm text-slate-500">Manage the directory, patients and appointment operations.</p></div><button onClick={()=>setShowAdd(true)} className="btn-primary"><Plus size={18}/> Add doctor</button></div>
      <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><M label="Total bookings" v={stats.totalBookings||0} icon={CalendarDays}/><M label="Active doctors" v={stats.activeDoctors||0} icon={Activity}/><M label="Patients" v={stats.patients||0} icon={UsersRound}/><M label="Completed revenue" v={formatCurrency(stats.revenue)} icon={IndianRupee}/></div>
      <div className="mt-8 flex gap-2 overflow-x-auto border-b border-slate-200">{["overview","doctors","patients","appointments"].map(x=><button key={x} onClick={()=>setTab(x)} className={`border-b-2 px-4 py-3 text-sm font-bold capitalize ${tab===x?"border-teal-600 text-teal-700":"border-transparent text-slate-500"}`}>{x}</button>)}</div>
      {tab==="overview"&&<Overview appointments={appointments} doctors={doctors}/>}
      {tab==="doctors"&&<DoctorTable doctors={doctors} remove={remove}/>}
      {tab==="patients"&&<UserTable users={users}/>}
      {tab==="appointments"&&<AppointmentTable appointments={appointments}/>}
    </div></main>
    {showAdd&&<AddDoctor close={()=>setShowAdd(false)} reload={load}/>}
  </>;
}
function Overview({appointments,doctors}){const recent=appointments.slice(0,5);return <div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="card p-6"><h2 className="text-xl font-black text-ink">Recent bookings</h2><div className="mt-4 divide-y divide-slate-100">{recent.map(a=><div key={a._id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-bold text-ink">{a.patient?.name||"Patient"}</p><p className="text-xs text-slate-500">Dr. {a.doctor?.user?.name||"Doctor"} · {formatDate(a.date)} · {a.time}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold capitalize text-slate-600">{a.status}</span></div>)}</div></div><div className="card p-6"><h2 className="text-xl font-black text-ink">Directory health</h2><div className="mt-5 space-y-5"><Bar label="Verified doctors" value={doctors.filter(d=>d.verified).length} total={doctors.length}/><Bar label="Completed visits" value={appointments.filter(a=>a.status==="completed").length} total={appointments.length}/><Bar label="Confirmed visits" value={appointments.filter(a=>a.status==="confirmed").length} total={appointments.length}/></div></div></div>}
function Bar({label,value,total}){const pct=total?Math.round(value/total*100):0;return <div><div className="flex justify-between text-sm font-semibold"><span>{label}</span><span>{value}/{total}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-teal-600" style={{width:`${pct}%`}}/></div></div>}
function DoctorTable({doctors,remove}){return <div className="card mt-6 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-4">Doctor</th><th>Specialty</th><th>Location</th><th>Fee</th><th>Status</th><th/></tr></thead><tbody>{doctors.map(d=><tr key={d._id} className="border-t border-slate-100"><td className="px-5 py-4 font-bold text-ink">Dr. {d.user?.name}</td><td>{d.specialization}</td><td>{d.location}</td><td>{formatCurrency(d.fees)}</td><td><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-700">{d.user?.isActive?"Active":"Inactive"}</span></td><td><button onClick={()=>remove(d._id)} className="font-bold text-rose-600">Deactivate</button></td></tr>)}</tbody></table></div>}
function UserTable({users}){return <div className="card mt-6 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-4">Patient</th><th>Email</th><th>Phone</th><th>Joined</th></tr></thead><tbody>{users.map(u=><tr key={u._id} className="border-t border-slate-100"><td className="px-5 py-4 font-bold text-ink">{u.name}</td><td>{u.email}</td><td>{u.phone||"—"}</td><td>{formatDate(u.createdAt.slice(0,10))}</td></tr>)}</tbody></table></div>}
function AppointmentTable({appointments}){return <div className="card mt-6 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-4">Patient</th><th>Doctor</th><th>Date</th><th>Time</th><th>Status</th></tr></thead><tbody>{appointments.map(a=><tr key={a._id} className="border-t border-slate-100"><td className="px-5 py-4 font-bold text-ink">{a.patient?.name}</td><td>Dr. {a.doctor?.user?.name}</td><td>{formatDate(a.date)}</td><td>{a.time}</td><td className="capitalize">{a.status}</td></tr>)}</tbody></table></div>}
function AddDoctor({close,reload}){const [f,setF]=useState({name:"",email:"",password:"",specialization:"",location:"",fees:1000,experience:5});const [busy,setBusy]=useState(false);async function save(e){e.preventDefault();setBusy(true);try{await api.post("/admin/doctors",f);toast.success("Doctor added.");close();reload()}catch(e){toast.error(e.response?.data?.message||"Could not add doctor.")}finally{setBusy(false)}}return <div className="fixed inset-0 z-[60] grid place-items-center bg-ink/40 p-4"><form onSubmit={save} className="card max-h-[90vh] w-full max-w-lg overflow-auto p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-black text-ink">Add a doctor</h2><button type="button" onClick={close} className="text-slate-400">✕</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{["name","email","password","specialization","location","fees","experience"].map(k=><label key={k}><span className="label">{k[0].toUpperCase()+k.slice(1)}</span><input required className="input" type={["fees","experience"].includes(k)?"number":k==="email"?"email":"text"} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><button disabled={busy} className="btn-primary mt-6 w-full">{busy?<Spinner/>:"Create doctor"}</button></form></div>}
function M({label,v,icon:Icon}){return <div className="card p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-teal-600"><Icon size={19}/></span><Activity size={16} className="text-slate-300"/></div><p className="mt-5 text-xs font-semibold text-slate-400">{label}</p><p className="mt-1 text-2xl font-black text-ink">{v}</p></div>}
