import { CalendarCheck2, Check, Clock3, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import Navbar from "../components/Navbar";
import api from "../lib/api";
import { formatDate, formatCurrency, getInitials } from "../lib/format";
import { Spinner } from "../components/Loading";
import { useAuth } from "../context/AuthContext";

const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];

export default function DoctorDashboard(){
  const {doctor,setDoctor,user}=useAuth(); const [appointments,setAppointments]=useState([]); const [tab,setTab]=useState("appointments"); const [busy,setBusy]=useState(false);
  async function load(){try{const [a,d]=await Promise.all([api.get("/doctors/me/appointments"),api.get("/auth/me")]);setAppointments(a.data);setDoctor(d.data.doctor)}catch{toast.error("Could not load dashboard.")}}
  useEffect(()=>{load()},[]);
  async function status(id,status){setBusy(true);try{await api.patch(`/appointments/${id}/status`,{status});toast.success(`Appointment ${status}.`);load()}catch(e){toast.error(e.response?.data?.message||"Action failed.")}finally{setBusy(false)}}
  async function saveSchedule(schedule){setBusy(true);try{const r=await api.patch("/doctors/schedule",{schedule});setDoctor(r.data);toast.success("Working hours saved.")}catch(e){toast.error(e.response?.data?.message||"Could not save schedule.")}finally{setBusy(false)}}
  const pending=appointments.filter(a=>a.status==="pending"); const active=appointments.filter(a=>["pending","confirmed"].includes(a.status));

  return <>
    <Navbar/><main className="min-h-screen bg-slate-50/70 py-8"><div className="container-app">
      <div className="rounded-3xl bg-gradient-to-r from-ink to-teal-800 p-7 text-white"><p className="text-sm text-teal-100">Doctor workspace</p><h1 className="mt-1 text-3xl font-black">Good morning, Dr. {user?.name?.split(" ")[0]}.</h1><p className="mt-2 text-sm text-slate-300">A clear view of today's patients and your schedule.</p></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={CalendarCheck2} label="Requests" value={pending.length}/><Metric icon={Clock3} label="Active visits" value={active.length}/><Metric icon={UserRound} label="Consultation fee" value={formatCurrency(doctor?.fees)}/></div>
      <div className="mt-8 flex gap-2 overflow-x-auto border-b border-slate-200"><button onClick={()=>setTab("appointments")} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-bold ${tab==="appointments"?"border-teal-600 text-teal-700":"border-transparent text-slate-500"}`}>Appointments</button><button onClick={()=>setTab("schedule")} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-bold ${tab==="schedule"?"border-teal-600 text-teal-700":"border-transparent text-slate-500"}`}>Working hours</button><button onClick={()=>setTab("profile")} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-bold ${tab==="profile"?"border-teal-600 text-teal-700":"border-transparent text-slate-500"}`}>Profile</button></div>

      {tab==="appointments"&&<div className="mt-6 space-y-4">{appointments.length?appointments.map(a=><div key={a._id} className="card p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-teal-50 font-black text-teal-700">{getInitials(a.patient?.name)}</div><div><p className="text-lg font-black text-ink">{a.patient?.name}</p><p className="mt-1 text-sm text-slate-500">{formatDate(a.date)} · {a.time} · {a.patient?.phone||"Phone not provided"}</p><p className="mt-2 text-sm text-slate-600">{a.reason||"No reason provided."}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize text-slate-600">{a.status}</span>{a.status==="pending"&&<><button disabled={busy} onClick={()=>status(a._id,"confirmed")} className="btn-primary px-3 py-2 text-sm"><Check size={15}/> Accept</button><button disabled={busy} onClick={()=>status(a._id,"rejected")} className="rounded-xl bg-rose-50 px-3 py-2 text-sm font-bold text-rose-600"><X size={15}/> Reject</button></>}{a.status==="confirmed"&&<button disabled={busy} onClick={()=>status(a._id,"completed")} className="btn-secondary px-3 py-2 text-sm">Mark completed</button>}</div></div></div>):<div className="card p-10 text-center text-slate-500">No appointments yet.</div>}</div>}

      {tab==="schedule"&&<Schedule doctor={doctor} onSave={saveSchedule} busy={busy}/>}
      {tab==="profile"&&<Profile doctor={doctor} onSaved={setDoctor}/>}
    </div></main>
  </>;
}

function Schedule({doctor,onSave,busy}){const [s,setS]=useState(doctor?.schedule||[]);useEffect(()=>setS(doctor?.schedule||[]),[doctor]);function patch(day,key,value){setS(prev=>{const found=prev.find(x=>x.day===day);if(found)return prev.map(x=>x.day===day?{...x,[key]:value}:x);return [...prev,{day,start:"09:00",end:"17:00",enabled:false,[key]:value}]})}return <div className="card mt-6 p-6"><div className="flex items-end justify-between"><div><h2 className="text-xl font-black text-ink">Working hours</h2><p className="mt-1 text-sm text-slate-500">Slots are generated every 30 minutes.</p></div><button disabled={busy} onClick={()=>onSave(s)} className="btn-primary">{busy?<Spinner/>:"Save hours"}</button></div><div className="mt-6 space-y-3">{[0,1,2,3,4,5,6].map(day=>{const x=s.find(v=>v.day===day)||{day,start:"09:00",end:"17:00",enabled:false};return <div key={day} className="grid items-center gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-[130px_90px_1fr_1fr]"><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={!!x.enabled} onChange={e=>patch(day,"enabled",e.target.checked)} />{days[day]}</label><span className="text-xs text-slate-400">Hours</span><input type="time" className="input" value={x.start} disabled={!x.enabled} onChange={e=>patch(day,"start",e.target.value)}/><input type="time" className="input" value={x.end} disabled={!x.enabled} onChange={e=>patch(day,"end",e.target.value)}/></div>})}</div></div>}

function Profile({doctor,onSaved}){const [f,setF]=useState({specialization:doctor?.specialization||"",location:doctor?.location||"",experience:doctor?.experience||0,fees:doctor?.fees||0,bio:doctor?.bio||"",photo:doctor?.photo||"",qualifications:(doctor?.qualifications||[]).join(", ")});const [busy,setBusy]=useState(false);async function save(e){e.preventDefault();setBusy(true);try{const r=await api.patch("/doctors/profile",{...f,experience:Number(f.experience),fees:Number(f.fees),qualifications:f.qualifications.split(",").map(x=>x.trim()).filter(Boolean)});onSaved(r.data);toast.success("Profile updated.")}catch(e){toast.error(e.response?.data?.message||"Could not update profile.")}finally{setBusy(false)}}return <form onSubmit={save} className="card mt-6 p-6"><h2 className="text-xl font-black text-ink">Public profile</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><F label="Specialization" v={f.specialization} set={v=>setF({...f,specialization:v})}/><F label="Location" v={f.location} set={v=>setF({...f,location:v})}/><F label="Experience (years)" type="number" v={f.experience} set={v=>setF({...f,experience:v})}/><F label="Consultation fee" type="number" v={f.fees} set={v=>setF({...f,fees:v})}/><F label="Photo URL" v={f.photo} set={v=>setF({...f,photo:v})}/><F label="Qualifications (comma separated)" v={f.qualifications} set={v=>setF({...f,qualifications:v})}/></div><label className="label mt-4">Bio<textarea className="input min-h-32" value={f.bio} onChange={e=>setF({...f,bio:e.target.value})}/></label><button disabled={busy} className="btn-primary mt-5">{busy?<Spinner/>:"Save profile"}</button></form>}
function F({label,v,set,type="text"}){return <label><span className="label">{label}</span><input className="input" type={type} value={v} onChange={e=>set(e.target.value)}/></label>}
function Metric({icon:Icon,label,value}){return <div className="card flex items-center gap-4 p-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-teal-50 text-teal-600"><Icon size={20}/></span><div><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-1 text-xl font-black text-ink">{value}</p></div></div>}
